[project]
name = "jpy-tillo-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "jpy-tillo-sdk>=0.2.0",
    "python-dotenv>=1.0.1",
]
